name: unofficial_mashov
description: The unofficial Mashov application
version: 1.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_typeahead: ^1.4.0
  mashov_api: ^0.1.0
  shared_preferences: ^0.5.2
  localstorage: ^1.2.0
  connectivity: ^0.4.3
  fab_menu: ^0.0.2
  rxdart: 0.21.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
