name: unofficial_mashov
description: The unofficial Mashov application
version: 1.3.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_typeahead: ^1.4.1
  mashov_api: ^0.2.0
  shared_preferences: ^0.5.2
  localstorage: ^1.3.0
  connectivity: ^0.4.3+1
  fab_menu: ^0.0.2
  rxdart: ^0.21.0
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
