name: unofficial_mashov
description: The unofficial Mashov application
version: 1.7.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_typeahead: ^1.6.1
  mashov_api: ^0.5.1
  shared_preferences: ^0.5.3+4
  localstorage: ^2.0.0
  connectivity: ^0.4.3+7
  fab_menu: ^0.0.2
  provider: ^3.0.0+1
  downloads_path_provider: ^0.1.0
  simple_permissions: ^0.1.9
  url_launcher: ^5.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
