name: unofficial_mashov
description: The unofficial Mashov application
version: 1.4.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_typeahead: ^1.5.0
  mashov_api: ^0.3.0
  shared_preferences: ^0.5.2
  localstorage: ^1.3.0
  connectivity: ^0.4.3+1
  fab_menu: ^0.0.2
  rxdart: ^0.22.0
  provider: ^3.0.0+1
  downloads_path_provider: ^0.1.0
  simple_permissions: ^0.1.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
